name: Secman Docker CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  SM_DOCKER_REPO: https://github.com/scmn-dev/docker
  SM_CONTAINER_DH_IMAGE: smcr/secman
  SM_CONTAINER_GHCR_IMAGE: ghcr.io/scmn-dev/secman
  SM_CLI_IMAGE: smcr/secman-cli

jobs:
  # Secman Container Docker Image `smcr/secman` | DockerHub
  sm_container_build_dh:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_SECMAN_TOKEN }}

      - name: Run Build
        run: |
          docker pull $SM_CONTAINER_DH_IMAGE:latest
          git clone $SM_DOCKER_REPO
          docker build -t $SM_CONTAINER_DH_IMAGE --cache-from $SM_CONTAINER_DH_IMAGE:latest --file ./docker/container/Dockerfile .
          docker push $SM_CONTAINER_DH_IMAGE

  sm_container_run_dh:
    needs: [ sm_container_build_dh ]

    runs-on: ubuntu-latest

    container:
      image: smcr/secman:latest

    steps:
      - name: Run Secman in Docker Container
        run: |
          secman

  # Secman Container Docker Image `smcr/secman` | GitHub Packages
  sm_container_build_ghcr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Github Packages
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Run Build
        run: |
          docker pull $SM_CONTAINER_GHCR_IMAGE:latest
          git clone $SM_DOCKER_REPO
          docker build -t $SM_CONTAINER_GHCR_IMAGE --cache-from $SM_CONTAINER_GHCR_IMAGE:latest --file ./docker/container/Dockerfile .
          docker push $SM_CONTAINER_GHCR_IMAGE

  sm_container_run_ghcr:
    needs: [ sm_container_build_ghcr ]

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/scmn-dev/secman:latest

    steps:
      - name: Run Secman in Github Docker Container
        run: |
          secman

  # Secman CLI Docker Image `smcr/secman-cli`
  sm_cli_build:
    needs: [ sm_container_build_dh, sm_container_run_dh, sm_container_build_ghcr, sm_container_run_ghcr ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_SECMAN_TOKEN }}

      - name: Build Secman CLI
        run: |
          docker pull $SM_CLI_IMAGE:latest
          git clone $SM_DOCKER_REPO
          wget https://docker.secman.dev/secman
          chmod 755 secman
          docker build -t $SM_CLI_IMAGE --cache-from $SM_CLI_IMAGE:latest --file ./docker/cli/Dockerfile .
          docker push $SM_CLI_IMAGE

  sm_cli_run:
    needs: [ sm_cli_build ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Secman CLI in Docker Container
        run: |
          # run `secman`
          docker run --rm -i $SM_CLI_IMAGE

          # run `secman version`
          docker run --rm -i $SM_CLI_IMAGE ver
