name: Secman CI

on:
  push:
    branches: [ v1 ]

  pull_request:
    branches: [ v1 ]

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  CLONE_DOT_SECMAN: git clone https://github.com/scmn-dev/.secman.ex

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install secman (Linux)
        run: curl -fsSL https://cli.secman.dev/unix | bash

      - name: Clone .secman (ex folder)
        run: $CLONE_DOT_SECMAN /home/runner/.secman

      - name: Run secman
        run: secman

      - name: Run secman Help
        run: secman -h

      - name: Run secman version
        run: secman ver

  # macos:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Config
  #       run: $CONFIG_NAME

  #     - name: Install secman (MacOS)
  #       run: curl -fsSL https://cli.secman.dev/unix | bash

  #     - name: Clone .secman (ex folder)
  #       run: |
  #         echo $HOME
  #         $CLONE_DOT_SECMAN ~/.secman

  #     - name: Run secman
  #       run: secman

  #     - name: Run secman Help
  #       run: secman -h

  #     - name: Run secman version
  #       run: secman ver

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build secman (MacOS)
        run: |
          git clone https://github.com/scmn-dev/secman-v1 secman
          cd secman
          make
          make setup

      - name: Clone .secman (ex folder)
        run: |
          $CLONE_DOT_SECMAN ~/.secman

      - name: Run secman
        run: secman

      - name: Run secman Help
        run: secman -h

      - name: Run secman version
        run: secman ver

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install secman (Windows)
        run: |
          iwr -useb https://cli.secman.dev/win | iex
          echo "::add-path::C:\Users\runneradmin\AppData\Local\secman\bin\;"

      - name: Clone .secman (ex folder)
        shell: powershell
        run: git clone https://github.com/scmn-dev/.secman.ex C:\Users\runneradmin\.secman

      - name: Run secman
        run: secman

      - name: Run secman Help
        run: secman -h

      - name: Run secman version
        run: secman ver
